import Head from 'next/head'
import { Inter } from 'next/font/google'
import React from 'react';
import CV from '@/components/cv';

export const inter = Inter({ subsets: ['latin'] });

export default function Home() {

  return (
    <>
      <Head>
        <title>CV ALDO RATMAWAN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/image/my-foto.png" />
         <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"/>
      </Head>
      <CV/>
    </>
  )
}
Home.getLayoutIndex = function (page: any) {
  return page;
} 
